server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      server:
        webflux:
          routes:
            - id: users-route
              uri: lb://user-service
              predicates:
                - Path=/users/**
            - id: transactions-route
              uri: lb://transaction-service
              predicates:
                - Path=/transactions/**
            - id: holdings-route
              uri: lb://holding-service
              predicates:
                - Path=/holdings/**
            - id: websocket-route
              uri: ws://localhost:8082
              predicates:
                - Path=/ws/**
            - id: login
              uri: lb://user-service
              predicates:
                - Path=/login
            - id: protected
              uri: lb://user-service
              predicates:
                - Path=/protected
logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
eureka:
  instance:
    prefer-ip-address: true
